/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                           (c) Copyright 1992-1999, Jean J. Labrosse, Weston, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
*********************************************************************************************************
*/
#ifndef INCLUDES_H
#define INCLUDES_H

#include "os_cpu.h"
#include "os_cfg.h"
#include "ucos_ii.h"

#endif
